Refactored some Stuff and added NullPointerException prevention.
Der-Zauberer/HarryPotterPlugin pull request #1
Opened 2022-06-18 14:12 UTC by AhegaHOE

I fixed some NullPointerException issues. Some of your code is pretty unsafe in terms of NullPointers.

Also I added Lambok that helps you generate Getters and Setters. You simply have to Annotate the Fields (or the Class) with @Getter @Setter depending on your needs.

2022-06-19 20:39 UTC, Der-Zauberer commented
Thank you for your help, I appreciate your work for that project. I will check your out your PR in the next days.

2022-06-20 19:59 UTC, MrTroble requested changes

2022-06-20 19:59 UTC, MrTroble commented on src/harrypotterplugin/items/GoldenFeatherItem.java
> +                    if (Objects.requireNonNull(itemStack.getItemMeta()).hasEnchant(Enchantment.DURABILITY)) {
This is indeed unsafer as it was before. Objects.requireNonNull throws a NPE if the given parameter ist null See: https://docs.oracle.com/javase/8/docs/api/java/util/Objects.html#requireNonNull-T-java.lang.String-

So this code crashes if the `itemStack` is null or `itemStack.getItemMeta()` is null, such as using your bare hands

2022-06-20 19:59 UTC, MrTroble commented on src/harrypotterplugin/spells/StuporSpell.java
> +			SpellProjectile spellProjectile = new SpellProjectile(1, 40, Objects.requireNonNull(event.getPlayer()).getEyeLocation(), event.getPlayer().getEyeLocation().getDirection());
Again the same issue this crashes with an NPE, but the player can never be null in this case

2022-06-20 19:59 UTC, MrTroble commented on src/harrypotterplugin/utilities/PlayerStats.java
> +	@Getter
There is no need to use this library you can auto generate getter and setter in eclipse, this is unneeded overhead

2022-06-20 19:59 UTC, MrTroble commented on src/harrypotterplugin/utilities/SpellProjectile.java
> +				Collection<Entity> entities = Objects.requireNonNull(location.getWorld()).getNearbyEntities(location, 0.1, 0.1, 0.1);
Same issue here this fixes nothing but it crashes again

2022-06-20 20:06 UTC, MrTroble commented
Your refactoring is good and some minor changes but using a library to create getter and setter on the fly is unneeded overhead and getter setter can be auto generated with there respective documentation in your IDE. The [Objects.requireNonNull](https://docs.oracle.com/javase/8/docs/api/java/util/Objects.html#requireNonNull-T-) throws a Nullpointer Exception which is never catched by the program hence it will crash again. This does not improve null pointer safety but actually produces more bugs such as mentioned in on of the comments.

Cheers
~MrTroble

2022-06-20 21:01 UTC, AhegaHOE commented
I'll take care of the NPE safety. Actually i have to say that i rushed over that one, so it's my bad. Sorry for that one, as soon as i get the time i'll change those.

2022-06-20 21:07 UTC, MrTroble commented
> I'll take care of the NPE safety. Actually i have to say that i rushed over that one, so it's my bad. Sorry for that one, as soon as i get the time i'll change those.

Thank you for your work! 
If you need any help implementing or if you should have questions, don't hesitate to ask.

While I am not the original Implementor, I might be able to help.

Cheers
~MrTroble

2022-06-20 21:16 UTC, AhegaHOE commented
It's actually my first time contributing to am open source project like that. Thank you for the offer! I'll look forward to let you know if i need any help. I'll take my time and resolve those issues.

I'm very grateful for your review.

2022-06-20 21:34 UTC, AhegaHOE commented
I hope all is fixed now. Please let me know if anything's still wrong.

2022-06-21 17:23 UTC, Der-Zauberer reviewed
Thank you for your help, I will cherry pick your refectoring and some of the NPE stuff.

2022-06-21 17:23 UTC, Der-Zauberer commented on src/harrypotterplugin/items/BroomStickItem.java
> +            if(itemStack.getItemMeta() == null) return;
The itemStack can not be null, because this is already filtered by the ExtendedItemStack.

https://github.com/Der-Zauberer/HarryPotterPlugin/blob/main/src/harrypotterplugin/utilities/ExtendedItemStack.java#L212-L214
https://github.com/Der-Zauberer/HarryPotterPlugin/blob/main/src/harrypotterplugin/utilities/ExtendedItemStack.java#L174-L179

2022-06-21 17:23 UTC, Der-Zauberer commented on src/harrypotterplugin/items/GoldenFeatherItem.java
> +                    if(itemStack.getItemMeta() == null) return;
This itemMeta can also not be null, because this is filtered by the isItem() Method.

https://github.com/Der-Zauberer/HarryPotterPlugin/blob/main/src/harrypotterplugin/utilities/ExtendedItemStack.java#L183

2022-06-21 17:23 UTC, Der-Zauberer commented on src/harrypotterplugin/main/HarryPotterPlugin.java
> +        if (harryPotterCommand != null) harryPotterCommand.setExecutor(new HarryPotterCommand());
This is unneccessary, because the command is created by the developer and will never change during runtime.

2022-06-21 17:27 UTC, Der-Zauberer commented
The PR is merged: https://github.com/Der-Zauberer/HarryPotterPlugin/commit/ec8f05850c13b32c5ba4119c39742156e452f0a4

2022-06-21 17:27 UTC, closed without merging

2022-06-22 13:54 UTC, MrTroble commented
> It's actually my first time contributing to an open source project like that. Thank you for the offer! I'll look forward to let you know if i need any help. I'll take my time and resolve those issues.
> 
> I'm very grateful for your review.

Well done for your first time 👍

2022-06-22 14:44 UTC, AhegaHOE commented
Thank you! :D